# Generated by Django 4.2.5 on 2023-10-04 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_producto_pub_date_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='curso_images/'),
            preserve_default=False,
        ),
    ]
